### ISSUE TITLE
Helix 3 Migration

### ISSUE THREAD

**Issue by maxakuru** [adobe/pages#361]
Code-related steps for Helix 3 migration of pages.adobe.com, see https://github.com/adobe/project-helix/issues/604

## Preparation
- [x] Use `main` branch #328 
- [x] Add client-side embed insertions #339 
- [x] Isolate templates; `default.css`, `global.css`, etc #339 
- [x] Type definitions for global namespace, `BlockDecorator`, `Component`
- [x] Sample block directory
- [x] Update README; inner CDN link, dev setup, scripts #362
- [x] Parameterize comparisons script #364
- [x] Sync code to code bus
- [x] QA comparisons
  - `https://main--pages--adobe.hlx.live/` (hlx3) vs. `https://pages.adobe.com/` (expected)
  - See the comparison [pagelist](https://github.com/adobe/pages/blob/main/.tools/pagelist.js) for pathnames tested

### During migration
- [x] Change default branch to `main` #328

### After migration
- [x] QA comparisons
  - `https://pages.adobe.com/` (migrated) vs. `https://pages-adobe.hlx.page/` (expected)
